dist: trusty
language: node_js
node_js:
  - "4.5.0"
install:
  - npm i -g yarn
  - make install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./node_modules/.bin/selenium-standalone start 2>&1 &"
  - sleep 5
script:
  - make build
  - make test
cache:
  directories:
    - node_modules
branches:
  only:
    - master
